/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as DevigRouteImport } from './routes/devig'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as KellyRouteImport } from './routes/kelly'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecordRouteImport } from './routes/record'
import { Route as ScreenRouteImport } from './routes/screen'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const DevigRoute = DevigRouteImport.update({
  id: '/devig',
  path: '/devig',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const KellyRoute = KellyRouteImport.update({
  id: '/kelly',
  path: '/kelly',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenRoute = ScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brain': typeof BrainRoute
  '/devig': typeof DevigRoute
  '/engine': typeof EngineRoute
  '/journal': typeof JournalRoute
  '/kelly': typeof KellyRoute
  '/login': typeof LoginRoute
  '/record': typeof RecordRoute
  '/screen': typeof ScreenRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brain': typeof BrainRoute
  '/devig': typeof DevigRoute
  '/engine': typeof EngineRoute
  '/journal': typeof JournalRoute
  '/kelly': typeof KellyRoute
  '/login': typeof LoginRoute
  '/record': typeof RecordRoute
  '/screen': typeof ScreenRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brain': typeof BrainRoute
  '/devig': typeof DevigRoute
  '/engine': typeof EngineRoute
  '/journal': typeof JournalRoute
  '/kelly': typeof KellyRoute
  '/login': typeof LoginRoute
  '/record': typeof RecordRoute
  '/screen': typeof ScreenRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/brain'
    | '/devig'
    | '/engine'
    | '/journal'
    | '/kelly'
    | '/login'
    | '/record'
    | '/screen'
    | '/settings'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/brain'
    | '/devig'
    | '/engine'
    | '/journal'
    | '/kelly'
    | '/login'
    | '/record'
    | '/screen'
    | '/settings'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/brain'
    | '/devig'
    | '/engine'
    | '/journal'
    | '/kelly'
    | '/login'
    | '/record'
    | '/screen'
    | '/settings'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BrainRoute: typeof BrainRoute
  DevigRoute: typeof DevigRoute
  EngineRoute: typeof EngineRoute
  JournalRoute: typeof JournalRoute
  KellyRoute: typeof KellyRoute
  LoginRoute: typeof LoginRoute
  RecordRoute: typeof RecordRoute
  ScreenRoute: typeof ScreenRoute
  SettingsRoute: typeof SettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devig': {
      id: '/devig'
      path: '/devig'
      fullPath: '/devig'
      preLoaderRoute: typeof DevigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kelly': {
      id: '/kelly'
      path: '/kelly'
      fullPath: '/kelly'
      preLoaderRoute: typeof KellyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen': {
      id: '/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BrainRoute: BrainRoute,
  DevigRoute: DevigRoute,
  EngineRoute: EngineRoute,
  JournalRoute: JournalRoute,
  KellyRoute: KellyRoute,
  LoginRoute: LoginRoute,
  RecordRoute: RecordRoute,
  ScreenRoute: ScreenRoute,
  SettingsRoute: SettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
